### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Immortalin** [kumavis/node-blockly-js-editor#5]
I don't suppose that you might plan to complete this or extend support for python ;)?

**Comment by Immortalin** [comment]
@kumavis do you think you can add support for python? A quick Google for `python AST to xml` turns up quite a few results. While I would love to send you a pull request, my coding skills are nowhere near your level

**Comment by kumavis** [comment]
i havent touched this repo in a few years -- you're welcome to do with it what you like, not sure when ill get the chance to pick it up again
